== Use Case Template

Version 1.20

*Instructions for removing the ‘Hints, Guidelines and Examples’ from
this document*

After you have completed the Use Case document, you may want to remove
the hints and guidelines provided in the document.

To remove the hints: (This procedure applies to Microsoft Word XP and
higher)

[arabic]
. Click on any text formatted as Hint.
. Then, click the right mouse button.
. A pop-up menu will appear, choose ‘Select text with similar
formatting’
. All Hint text will now be selected in the document.
. *Ensure that none of the text that you have entered is in the
selection.*
. Press the _Delete_ key to remove the _Hints , Guidelines and
examples._.

=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
| 13/10/19| Kévin ROY| Initialisation du document
| 23/10/19 | Kévin ROY | Précision sur le scénario de succès. (UC-1.2.1)
| | |
| | |
| | |
| | |
| | |
|===

Use Case Template. Copyright (c) 2004-2005 TechnoSolutions Corporation

(Learn more about “TopTeam for Use Cases” at
http://www.technosolutions.com[[.underline]#www.technosolutions.com#])

Permission is hereby granted, free of charge, to any person obtaining a
copy of this document and its associated documentation, to use the
document on their projects for any commercial or non-commercial purpose.
However you may not publish, distribute, sublicense, and/or sell copies
of this document.

THE DOCUMENT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
DOCUMENT OR THE USE OR OTHER DEALINGS IN THE DOCUMENT. TECHNOSOLUTIONS
CORPORATION MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THIS
DOCUMENT FOR ANY PURPOSE. +

*Use Case:* Donner Mission Tous Les Joueurs

*Id*: UC-1.2

*Description*

Le jeu attribut des missions aux joueurs,
chaque joueur se retrouve donc avec une et une seule carte mission,
le reste des cartes missions est enlevé.


*Level:* <Enter Use Case Goal Level here>

<Enter the goal level of this Use Case. Specify whether the Use Case
level is - High Level Summary, Summary, User Goal, Sub-Function, Low
Level>

*Primary Actor*

Le Jeu

*Supporting Actors*

Aucun


*Stakeholders and Interests*

Joueurs

*Pre-Conditions*

Toutes les missions possibles on été chargés.

*Post Conditions*

[.underline]#Success end condition#

Tous les joueurs ont réçu une et une seule carte mission unique.

[.underline]#Failure end condition#:

Un ou plusieurs joueurs n'ont pas de mission, ou deux joueurs ont la même mission.

[.underline]#Minimal Guarantee#


*Trigger*

Initialisation

=== Main Success Scenario

[arabic]
. Le jeu a la liste des missions.
. Il attribut une des missions de la liste au joueur 1 puis retire cette mission de la liste (UC-1.2.1)
. Il répète l'instruction précédente pour tous les autres joueurs.
. Il se termine si tous les joueurs ont reçu une mission différente


=== Extensions



=== Variations



=== Special Requirements 



=== Issues 



=== To do

[arabic]
. Ajouter le level du use case


To learn more about “TopTeam Analyst for Use Cases” visit
http://www.technosolutions.com[[.underline]#www.technosolutions.com#]
