=== Revision History +

[cols=",,",options="header",]
|===
|Date |Auteur |Description
| 16/10/19| Soline LECOMTE| Initialisation du document
| 26/10/19| Josselin Enet|Correction de l'orthographe
| | |
| | |
| | |
| | |
| | |
|===

*Use Case:* Initialisation du jeu

*Id*: UC-1

*Description*

Le jeu initialise la partie en mettant en place la préparation (Distribution des armées, Gestion des territoires, Distribution des missions, Placement des unités).

*Niveau:* 

*Acteur Principal*

Le jeu.

*Acteurs Secondaires*

Les joueurs.

*Parties Prenantes*

Les joueurs n'interagissent avec le jeu que pour déployer leur armées, mais c'est à eux que toute la phase profitera, puisque c'est grâce à cela qu'ils pourront commencer à jouer.

*Pre-Conditions*

Au moins 2 joueurs sont connectés sur le jeu.

*Post Conditions*

[.underline]#Condition de fin avec succès#

L'initialisation du jeu est terminée et les joueurs peuvent alors commencer la partie.

[.underline]#Condition de fin avec échec#

Le jeu n'a pas tout initialisé correctement : 
	- La distribution des armées n'est pas faite ou pas correctement
OU	- Les territoires ne sont pas distribués
OU	- Les missions n'ont pas été distribuées
OU	- Les unités n'ont pas été placées

*Déclenchement*

Les joueurs commandent le lancement d'une partie.

=== Scénario principal de succès

[arabic]
. Le jeu attribue une couleur à chaque Joueur (UC 1.1)
. Le jeu distribue une mission à chaque joueur (UC 1.2)
. Le jeu distribue les unités aux joueurs (UC 1.3)
. Le jeu distribue les territoires aux joueurs (UC 1.4)
. Le jeu laisse les joueurs déployer leurs unités (UC 1.5)

=== Extensions


=== Variations

*Fréquence:* Une fois par partie.

=== Special Requirements 

=== Instantané


=== Issues 

[arabic]


=== To do

[arabic]
Find possible Extensions/Variations/Special Requirements/Issues for this Use Case
Gérer le level du UC

