=== Modifications

[cols=",,",options="header",]
|===
|Date |Auteur |Description
| 16/10/19| Soline LECOMTE| Initialisation du document
| 26/16/19| Josselin Enet| Correction de l'orthographe
| | |
| | |
| | |
| | |
| | |
|===


*Use Case:* Distribuer des unités

*Id*: UC-1.3

*Description*

Le jeu distribue des unités à chaque joueur.

*Niveau:* 

*Acteur Principal*

Le jeu.

*Parties Prenantes*

Ce cas d'utilisation permettra aux joueurs de pouvoir déployer leurs unités et d'ensuite commencer la partie.

*Pre-Conditions*

Au moins 2 joueurs sont connectés sur le jeu.

*Post-Conditions*

[.underline]#Condition de fin avec succès#

Le jeu a distribué le bon nombre d'unités à chaque joueur.

[.underline]#Condition de fin avec échec#

Le jeu a distribué le mauvais nombre d'unités aux joueurs.

*Déclenchement*

Le jeu a distribué une mission à chaque joueur, l'initialisation de la partie continue avec ce cas d'utilisation.


=== Scénario principal de succès

[arabic]
. En fonction du nombre de joueurs, le jeu distribue un nombre identique d'armées à chaque joueur.


=== Extensions

Extension du step 1 : 

1a. S'il y a 3 joueurs :
		- Le jeu distribue 35 armées à chacun.
1b. S'il y a 4 joueurs :
		- Le jeu distribue 30 armées à chacun.
1c. S'il y a 5 joueurs :
		- Le jeu distribue 25 armées à chacun.
1d. S'il y a 6 joueurs :
		- Le jeu distribue 20 armées à chacun.



*Fréquence:* Une fois par partie.


=== Besoins spéciaux


=== To do

[arabic]
. {blank}

Find possible Extensions/Variations/Special Requirements/Issues for this Use Case
Gérer le level du UC
