=== Modifications

[cols=",,",options="header",]
|===
|Date |Auteur |Description
| 20/10/19 | Lenormand Tristan | Création du Use Case
| 26/10/19 | Josselin Enet | Correction de l'orthographe
| 31/10/19 | Soline LECOMTE | Ajout Snapshot
| | |
| | |
| | |
| | |
|===

*Use Case:* Donner les territoires

*Id*: UC-1.4

*Description*

Distribuer toutes les cartes territoires entre tous les joueurs.

*Niveau:* 

*Acteur Principal*

Le jeu.

*Acteurs Secondaires*

Tous les joueurs.

*Pre-Conditions*

Les joueurs n'ont pas de cartes territoire.
La pioche est pleine.

*Post Conditions*

[.underline]#Condition de fin avec succès#

Chaque joueur a le même nombre de cartes territoire à 1 carte près.
La pioche est vide et toutes les cartes ont été distribuées.

[.underline]#Condition de fin avec échec#

Toutes les cartes n'ont pas été distribuées.
Tous les joueurs n'ont pas le même nombre de cartes territoire à une carte près.

*Déclenchement*

Début de partie : fin du Use Case Donner unités (UC-1.3)

=== Scénario principal de succès

[arabic]
. Le jeu donne une carte territoire au joueur i
. Le jeu donne une carte territoire au joueur i+1
. On recommence cette étape jusqu'à ce que toutes les cartes de la pioche soient épuisées


=== Extensions



=== Variations



*Assumptions*


=== Special Requirements 

=== Instantané
Distribution des territoires dans une partie avec 3 joueurs.

[.underline]#Début:#

[plantuml, territoire-snap-start, png]
----
@startuml

Object joueur1 {
        nom = "J1"
        territoires = []
}

Object joueur2 {
        nom = "J2"
        territoires = []
}

Object joueur3 {
        nom = "J3"
        territoires = []
}

@enduml
----

[.underline]#Fin:#
[plantuml, territoire-snap-end, png]
----
@startuml	

Object joueur1 {
        nom = "J1"
        territoires = [Afghanistan, Inde, Afrique du Nord, Indonésie,	Afrique du Sud	, Islande, Afrique Orientale, Japon, Alaska, Kamchatka, Alberta, Madagascar, Amérique Centrale, Mongolie]
}

Object joueur2 {
        nom = "J2"
        territoires = [Argentine, Moyen Orient, Australie Occidentale, Nouvelle Guinée, Australie orientale Ontario	, Brésil,	Oural, Chine, Pérou,	Congo, Québec, Egypte, Scandinavie]
}

Object joueur3 {
        nom = "J3"
        territoires = [Etat de l'Est, Siam, Etat de l'Ouest, Sibérie,	 Europe du Nord, Tchita, Europe du Sud, Territoire du Nord Ouest, Europe Occidentale, Ukraine, Grande Bretagne, Venezuela, Groenland, Yakoutie]
}

@enduml
----

=== Issues 



=== To do

[arabic]
. {blank} Compléter Extension/Variations/Special Requirements/Issues

