== Use Case Template

=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
| 16/10/19| Soline LECOMTE| Initialisation du document
| | |
| | |
| | |
| | |
| | |
| | |
|===

Use Case Template. Copyright (c) 2004-2005 TechnoSolutions Corporation

(Learn more about “TopTeam for Use Cases” at
http://www.technosolutions.com[[.underline]#www.technosolutions.com#])

Permission is hereby granted, free of charge, to any person obtaining a
copy of this document and its associated documentation, to use the
document on their projects for any commercial or non-commercial purpose.
However you may not publish, distribute, sublicense, and/or sell copies
of this document.

THE DOCUMENT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
DOCUMENT OR THE USE OR OTHER DEALINGS IN THE DOCUMENT. TECHNOSOLUTIONS
CORPORATION MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THIS
DOCUMENT FOR ANY PURPOSE. +
*Use Case:* Initialisation du jeu

*Id*: UC-1

*Description*

Le jeu initialise la partie en mettant en place la préparation (Distribution des armées, Gestion des territoires, Distribution des missions, Placement des unités)

*Level:* <Enter Use Case Goal Level here>

<Enter the goal level of this Use Case. Specify whether the Use Case
level is - High Level Summary, Summary, User Goal, Sub-Function, Low
Level>

*Primary Actor*

Le jeu

*Supporting Actors*

Les joueurs

*Stakeholders and Interests*

Les joueurs n'intéragissent le jeu que pour déployer leur armées, mais c'est à eux que toute la phase profitera, puisque c'est grâce à cela qu'ils pourront commencer à jouer.


*Pre-Conditions*

Au moins 3 joueurs sont connectés sur le jeu.

*Post Conditions*

[.underline]#Success end condition#

L'initialisation du jeu est terminée et les joueurs peuvent alors commencer la partie.

[.underline]#Failure end condition#:

<List failure end condition here>

Le jeu n'a pas tout initialisé correctement : 
	- La distribution des armées n'est pas faite ou pas correctement
OU	- Les territoires ne sont pas distribués
OU	- Les missions n'ont pas été distribuées
OU	- Les unités n'ont pas été placées

[.underline]#Minimal Guarantee#

<List minimal guarantee here>


*Trigger*

Les joueurs commandent le lancement d'une partie.

=== Main Success Scenario

[arabic]
. Le jeu attribue une couleur à chaque Joueur (UC 1.1)
. Le jeu distribue une mission à chaque joueur (UC 1.2)
. Le jeu distribue les unités aux joueurs (UC 1.3)
. Le jeu distribue les territoires aux joueurs (UC 1.4)
. Le jeu laisse les joueurs déployer leurs unités (UC 1.5)

=== Extensions


=== Variations

*Frequency:* 

Une fois par partie


=== Special Requirements 


=== Issues 

[arabic]
. {blank}


=== To do

[arabic]
. {blank} 
Find possible Extensions/Variations/Special Requirements/Issues for this Use Case
Gérer le level du UC

