=== Revision History +

[cols=",,",options="header",]
|===
|Date |Author |Description of change
|28/10/2019 | Lenormand Tristan | Creation du Use Case
|31/10/2019 | Lecomte Soline | Corrections mineures
|04/11/2019 | Lenormand Tristan | Ajout Snapshot
| | |
| | |
| | |
| | |
|===

*Use Case:* Attaque d'un territoire ennemi par un joueur


*Id*: UC- 2.2


*Description*

Un joueur décide pendant son tour d'attaquer le territoire d'un autre joueur.
Il choisit donc le nombre d'armées sur son territoire avec lequel il attaque (1, 2 ou 3) puis
lance l'assault en lançant un nombre équivalaent de dés. Le défenseur fait de même pour se défendre (avec 1 ou 2 unités)
et le nombre d'unités perdues est alors calculé en comparant les dés les plus forts entre eux et les moins fort entre eux.
En cas d'égalité, c'est le defenseur qui l'emporte. Le combat se termine lorsque le defenseur n'a
plus d'unités ou que l'attaquant décide d'arrêter l'attaque ou qu'il na plus assez d'unités pour attaquer.
Si l'attaquant remporte l'offensive, il déplace sur le territoire conquis un nombre d'unités égal au nombre d'unités attaquantes lors de l'offensive.


*Level:* <Enter Use Case Goal Level here>


*Primary Actor*

Le joueur qui est en train de jouer son tour

*Supporting Actors*

Le joueur défenseur

*Stakeholders and Interests*

Les autres joueurs dont l'issue du combat peut contribuer à la progression de leurs objectifs. (éliminer un joueur)


*Pre-Conditions*

Le joueur attaquant a un nombre X d'unités sur le territoire attaquant.
Le joueur defenseur a un nombre Y d'unités sur le territoire defenseur.


*Post Conditions*

[.underline]#Success end condition#

-Le joueur defenseur n'a plus d'unités sur son territoire. Le joueur attaquant déplace le nombre d'unités qu'il a engagé
lors de l'attaque sur le territoire defenseur en laissant au minimum 1 unité sur le territoire d'origine.

-Le joueur attaquant n'a plus qu'une unité sur son territoire il a donc perdu l'attaque.

[.underline]#Failure end condition#:

Le joueur attaquant décide d'arrêter l'attaque et il n'y a donc pas de vainqueurs


[.underline]#Minimal Guarantee#

*Trigger*

Fin du UC-2.1 Renforts.

=== Main Success Scenario

[arabic]
. L'attaquant attaque avec un nombre i d'unités compris entre 1 et 3 et lance un même nombre de dés
. Le defenseur défend avec 1 ou 2 unités et lance un même nombre de dés
. On compare les dés entre eux (fort ensemble, faible ensemble) et les joueurs perdent une unités par dés perdant.
. Le combat continue jusqu'à que l'attaquant décide d'arrêter ou que l'attaquant n'aie plus qu'une unité, ou que le defenseur n'aie plus d'unités
. Si l'attaquant gagne, il déplace le nombre d'unités qu'il a engagé sur le territoire conquis

=== Extensions



=== Variations



=== Special Requirements 


=== Instantané

Résultat d'une attaque d'un joueur d'un territoire qu'il controle vers un territoire contrôlée par un autre joueur

[.underline]#Début:#
[plantuml, deploiement-unites-snap-start, png]
----
@startuml
object joueur1 {
        nom = "J1"
        couleur = "vert"
}

object joueur2 {
        nom = "J1"
        couleur = "vert"
}

Object unite1
Object unite2
Object unite3
Object unite4
Object unite5
Object unite6

Object territoireAttaque{
        nom = "Congo"
        appartient = "joueur1"
}

Object territoireDefense{
        nom = "Afrique du sud"
        appartient = "joueur2"
}


joueur1 -- unite1 : controle
joueur1 -- unite2 : controle
joueur1 -- unite3 : controle

joueur2 -- unite4 : controle
joueur2 -- unite5 : controle
joueur2 -- unite6 :controle

unite1 -- territoireAttaque : estPositionnée
unite2 -- territoireAttaque : estPositionnée
unite3 -- territoireAttaque : estPositionnée

unite4 -- territoireDefense : estPositionnée
unite5 -- territoireDefense : estPositionnée
unite6 -- territoireDefense : estPositionnée

unite1 -- territoireDefense : attaque
unite3 -- territoireDefense : attaque
@enduml
----
[.underline]#Fin:#
[plantuml, deploiement-unites-snap-end, png]
----
@startuml
object joueur1 {
nom = "J1"
couleur = "vert"
}

Object unite1
Object unite2
Object unite3

Object territoireAttaque{
nom = "Congo"
appartient = "joueur1"
}

Object territoireDefense{
        nom = "Afrique du sud"
        appartient = "joueur1"
}



joueur1 -- unite1 : controle
joueur1 -- unite2 : controle
joueur1 -- unite3 :controle

unite1 -- territoireDefense : estPositionnée
unite2 -- territoireAttaque : estPositionnée
unite3 -- territoireDefense : estPositionnée

@enduml

----


=== Issues 



=== To do

