== Modifications

[cols=",,",options="header",]
|===
|Date |Auteur |Description
|20/10/19| Josselin Enet|Création du Use Case
|26/10/19 | Josselin Enet|Correction de l'orthographe
|===


*Use Case:* Attribuer les couleurs

*Id*: UC-1.1


*Description*

Le jeu attribue à chaque joueur une couleur différente. Les unités et territoires de chaque joueur sont de couleur correspondante.

*Niveau:* <Enter Use Case Goal Level here>

*Acteur Principal*

Le jeu.

*Acteurs secondaires*

Les joueurs.

*Pre-Conditions*

La partie doit être lancée avec un nombre défini de joueurs, compris entre 2 et 6. Aucune unité ou territoire n'est attribué.

*Post-Conditions*

[.underline]#Condition de fin avec succès#

Chaque joueur se voit attribuer une couleur. Une couleur n'est pas affectée à 2 joueurs différents.

[.underline]#Condition de fin avec échec#

Un ou plusieurs joueurs n'ont pas de couleur attribuée.
Des joueurs ont la même couleur.


*Déclenchement*

La partie est lancée.

== Scénario principal de succès

[arabic]
. Plusieurs joueurs se connectent et lancent une partie.
. Le jeu attribue une couleur à chaque joueur.

*Fréquence:* Une fois au début de chaque partie.

== Besoins spéciaux

[.underline]#Interface#

. Chaque joueur doit pouvoir visualiser sa couleur ainsi que celle des autres joueurs.

== Instantané

Attribution des couleurs dans une partie avec 3 joueurs.

[.underline]#Début:#

[plantuml, couleur-snap-start, png]
----
@startuml

Object joueur1 {
        nom = "J1"
        couleur = ""
}

Object joueur2 {
        nom = "J2"
        couleur = ""
}

Object joueur3 {
        nom = "J3"
        couleur = ""
}

@enduml
----

[.underline]#Fin:#
[plantuml, couleur-snap-end, png]
----
@startuml

Object joueur1 {
        nom = "J1"
        couleur = "vert"
}

Object joueur2 {
        nom = "J2"
        couleur = "bleu"
}

Object joueur3 {
        nom = "J3"
        couleur = "rouge"
}

@enduml
----




=== To do

[arabic]
. Trouver le niveau du use case.

