== Modifications

[cols=",,",options="header",]
|===
|Date |Auteur |Description
|Josselin Enet | 26/10/19|Création du Use Case
|===

*Use Case:* Déplacer des unités

*Id*: UC-2.3

*Description*

Un joueur décide de déplacer certaines de ses unités depuis un de ses territoires vers un autre.

*Niveau:* 

*Acteur principal*

Le joueur en train d'effectuer son tour.

*Acteurs secondaires*

Les autres joueurs.

*Pre-Conditions*

Le joueur n'est pas éliminé.
Le territoire de départ possède plus d'une unité.
Le territoire de départ et celui d'arrivée appartiennent au joueur dont le tour est en cours.

*Post-Conditions*

[.underline]#Condition de fin avec succès#

Le joueur a pu déplacer ses unités vers le territoire souhaité.

[.underline]#Condition de fin avec échec#

Le joueur a déplacé ses unités vers un territoire avec lequel il ne devrait pas pouvoir interagir.
Il ne reste aucune unité sur le territoire de départ.
Le nombre d'unités enlevées au territoire de départ est différent de celui ajouté au territoire d'arrivée.

*Déclenchement*

Le joueur choisit certaines de ses unités qu'il souhaite déplacer.

== Scénario principal de succès

[arabic]
. Le joueur choisit des unités qui se situent sur un des territoires qu'il contrôle.
. Il sélectionne un autre de ses territoires.
. Les unités sont retirées au total des unités sur le territoire de départ et ajoutées au total de celui d'arrivée.

*Fréquence:* Autant de fois que souhaité par le joueur chaque tour.

== Besoins spéciaux

[.underline]#Interface#

{empty}1. Chaque déplacement d'unités d'un territoire vers un autre doit être visible par l'ensemble des joueurs.

{empty}2. Si plusieurs unités sont sélectionnées lors d'un même déplacement, alors une seule animation sera effectuée en affichant clairement le nombre d'unités déplacées.

== Instantané

Résultat d'un déplacement d'unités depuis le Congo vers l'Afrique du Nord.


[.underline]#Début:#
[plantuml, deplacement-snap-start, png]
----
@startuml

object joueur1 {
        nom = "J1"
        couleur = "vert"
}

Object unite1
Object unite2
Object unite3
Object unite4

Object terrDepart{
        nom = "Congo"
}

Object terrArrivee {
        nom = "Afrique du Nord"
}

joueur1 -- unite1 : controle
joueur1 -- unite2 : controle
joueur1 -- unite3 :controle
joueur1 -- unite4 :controle


unite1 -- terrDepart : estPositionnee
unite2 -- terrDepart : estPositionnee
unite3 -- terrDepart : estPositionnee
unite4 -- terrArrivee : estPositionnee

terrDepart -- terrArrivee : estVoisin

@enduml
----

[.underline]#Fin:#
[plantuml, deplacement-snap-end, png]
----
@startuml

object joueur1 {
        nom = "J1"
        couleur = "vert"
}

Object unite1
Object unite2
Object unite3
Object unite4

Object terrDepart{
        nom = "Congo"
}

Object terrArrivee {
        nom = "Afrique du Nord"
}

joueur1 -- unite1 : controle
joueur1 -- unite2 : controle
joueur1 -- unite3 :controle
joueur1 -- unite4 :controle


unite1 -- terrDepart : estPositionnee
unite2 -- terrArrivee : estPositionnee
unite3 -- terrArrivee : estPositionnee
unite4 -- terrArrivee : estPositionnee

terrDepart -- terrArrivee : estVoisin

@enduml
----



== Problèmes

[arabic]

1. Est-ce qu'on dit qu'on peut se déplacer vers un territoire adverse et dans ce cas on déclenche une attaque ou on sépare les deux?
2. Où est-ce qu'on dit qu'on peut effectuer plusieurs déplacement dans un tour? Ici ou dans le UC joueur un tour? 

