=== Modifications

[cols=",,",options="header",]
|===
|Date |Author |Description of change
| 02/11/19 | Kévin Roy | Initialisation du document
|===

*Use Case:* Fin de tour

*Id*: UC-2.4

*Description*

Le Joueur décide de terminer son tour, le jeu donne la main au joueur suivant.

*Niveau :* Fonction principale

*Acteur principal*

Joueur jouant son tour

*Acteurs secondaires*

Le Jeu

*Pre-Conditions*

Le Joueur a décidé de passer son tour.

*Post Conditions*

[.underline]#Condition de fin avec succès#

Le jeu passe la main au joueur suivant, c'est à dire que le joueur qui a terminé son tour ne peut plus jouer jusqu'au début de son prochain tour, et l'autre joueur dont le tour débute peut désormais jouer.

[.underline]#Condition de fin avec échec#

Le joueur ayant passé son tour peut encore jouer, ou l'autre joueur ne peut pas joueur alors quer le premier à terminé son tour.


*Déclenchement*

Le joueur jouant son tour indique qu'il le termine.

== Scénario principal de succès

[arabic]
. Le joueur jouant son tour décide de le terminer.
. Le jeu ne permet plus à ce joueur de jouer.
. Le jeu débute le tour du joueur suivant.



*Fréquence:* Une fois par tour, sauf si les conditions de victoire sont remplies, auquel cas la partie s'interrompt sans que le joueur passe son tour.


