= Project 2019: Risk

== Execution du programme

=== A installer :
- node js , pour executer nos commandes pour installer angular, bootstrap... téléchargeable en suivant ce lien : https://nodejs.org/en/
- angular en executant la commande : npm install -g @angular/cli
- bootstrap en executant la commande : npm install --save @ng-bootstrap/ng-bootstrap
- mysql

=== Mysql
Il faut configurer une base de données pour mysql afin que le programme puisse l'utiliser, les différentes informations concernant la base de données sont dans le fichier /main/ressources/application.properties.
De base la base de données à pour nom : db_risk.
Nom d'utilisateur : riskUser.
Mot de passe : riskPassword.

=== Execution
Une fois tout configuré il faut ouvrir deux terminal, un pour executer le programme et l'autre pour executer le client angular.
Pour le programme il suffit d'éxecuter le main dans AccessingDataMysqlApplication, et pour le client angular il faut ouvrir un invité de commande dans le dossier Client_angular et executer la commande suivant : ng serve.
Une fois executé il faut ouvrir un navigateur et accèder à la page localhost:4200.

=== Lancer une partie
Il est préférable d'ouvrir plusieurs onglets de cette page localhost pour pouvoir simuler plusieurs utilisateurs, ici 3 minimums sont nécessaires pour lancer la partie.
Pour lancer la partie il suffit de se connecter en rentrant un pseudo dans la barre de gauche et cliquer sur le bouton connecter.
Une fois fait avec les 3 utilisateurs, il faut cocher la case ready pour dire que les joueurs sont prêt, une fois fait la partie doit se lancer, c'est à dire que dans le chat a gauche il doit y avoir d'écrit que la partie et lancé et que l'initialisation a été effectué.


