:includedir: _chapters
= Projet 2019 : Risk

== Auteurs

[options="header"]
|===
| Nom       | Adresse 
| Josselin Enet | josselin.enet@etu.univ-nantes.fr
| Kévin Roy | kevin.roy2@etu.univ-nantes.fr
| Tristan Lenormand | tristan.lenormand@etu.univ-nantes.fr
| Soline Lecomte | soline.lecomte@etu.univ-nantes.fr
|===

== Introduction

Ce projet a pour but d'implémenter le jeu de plateau Risk. Nous commencerons par mener une analyse de domaine afin de mieux appréhender le sujet. Ensuite, nous expliquerons lors de la conception détailée nos choix de conception à haut niveau permettant de répondre aux exigences. Ces explications seront approfondies dans l'analyse détaillée, où nous nous assurerons de leur pertinence. Suite à ces étapes, le code source pourra être écrit et les tests unitaires mis en place. Nous pourrons terminer en effectuant une critique constructive des atouts et failles de notre projet.

== Organisation du document

. Analyse du domaine
.. Introduction
.. Cas d'utilisation
.. Modèle de classes du domaine
.. Invariants
.. Dictionnaire de données
.. Conclusion
. Conception préliminaire
.. Introduction
.. Description des composants
.. Composant GameServer
.. Composant WebClient
.. Interactions
. Conception détaillée
.. Composant GameServer
.. Composant WebClient
. Conclusion

// Chapters:

include::{includedir}/analyse-domaine.adoc[leveloffset=+1]
include::{includedir}/conception-preliminaire.adoc[leveloffset=+1]
include::{includedir}/conception-detaillee.adoc[leveloffset=+1]

== Conclusion

Points forts de votre projet

Limites (points faibles) de votre projet
