:includedir: _chapters
= Projet 2019 : Risk

== Auteurs

[options="header"]
|===
| Nom       | Adresse 
| Josselin Enet | josselin.enet@etu.univ-nantes.fr
| Kévin Roy | kevin.roy2@etu.univ-nantes.fr
| Tristan Lenormand | tristan.lenormand@etu.univ-nantes.fr
| Soline Lecomte | soline.lecomte@etu.univ-nantes.fr
|===

== Introduction

Ce projet a pour but d'implémenter le jeu de plateau Risk. Nous commencerons par mener une analyse de domaine afin de mieux appréhender le sujet. Ensuite, nous expliquerons lors de la conception détailée nos choix de conception à haut niveau permettant de répondre aux exigences. Ces explications seront approfondies dans l'analyse détaillée, où nous nous assurerons de leur pertinence. Suite à ces étapes, le code source pourra être écrit et les tests unitaires mis en place. Nous pourrons terminer en effectuant une critique constructive des atouts et failles de notre projet.

== Organisation du document

. Analyse du domaine
.. Introduction
.. Cas d'utilisation
.. Modèle de classes du domaine
.. Invariants
.. Dictionnaire de données
.. Conclusion
. Conception préliminaire
.. Introduction
.. Description des composants
.. Composant GameServer
.. Composant WebClient
.. Interactions
. Conception détaillée
.. Composant GameServer
.. Composant WebClient
. Conclusion

// Chapters:

include::{includedir}/analyse-domaine.adoc[leveloffset=+1]
include::{includedir}/conception-preliminaire.adoc[leveloffset=+1]
include::{includedir}/conception-detaillee.adoc[leveloffset=+1]

== Conclusion

La conception de notre projet nous parait cohérente avec les bonnes pratiques évoquées en cours : la structure de notre application semble relativement claire et le tout semble être maintenable et extensible sans difficulté majeure.
Cependant, de par l'utilisation de nouveaux outils (Angular, Spring...) et une organisation au mieux hasardeuse, nous n'avons pas pu mener à son terme le développement du système. Même si cela avait été le cas, certains points auraient sans doute mérités quelques améliorations. Par exemple, il est probable qu'il y aurait eu des failles de sécurité, permettant à des clients d'effectuer des actions qui devraient normalement leur être interdites, comme interagir avec d'autres parties, etc...
